"""Assemble the public release from this working folder (maintainers only):
  release/github/co-failure-ceiling/  -> the GitHub repo (code, paper source, protocol, docs; no data)
  release/hf/                         -> files uploaded to the HF dataset josefchen/co-failure-67-models
Everything the reproduction needs is listed explicitly below, so nothing private (response cache, secrets, working
notes) can leak into either target.
"""
import os, shutil, glob

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
GH = os.path.join(ROOT, "release", "github", "co-failure-ceiling")
HF = os.path.join(ROOT, "release", "hf")

GH_FILES = ["README.md", "DATA_AUDIT.md", "LICENSE", "CITATION.cff", "requirements.txt", "reproduce.sh", ".gitignore",
            "model_registry.csv", "market_registry.csv", "churn_registry.csv",
            "scripts/fetch_data.py", "scripts/check_numbers.py", "scripts/export_responses.py", "scripts/stage_release.py",
            "scripts/render_docs.py", "scripts/annotate_budgets.py", "scripts/publish_hf.py", "scripts/verify_grades.py", "scripts/export_spend_ledger.py", "scripts/build_arxiv.sh",
            "gpqa_open_v2/PROTOCOL.md", "gpqa_open_v2/items_original.json", "gpqa_open_v2/items_v2.json",
            "gpqa_open_v2/rater1_all.json",
            "paper/main.tex", "paper/numbers.tex", "paper/numbers_pillars.tex", "paper/references.bib", "paper/roster_rows.tex"]
LEGACY = ["recompute_tetrachoric.py", "bootstrap_ratio.py", "clayton_real.py", "residual_decomp.py", "codegen_analyze.py",
          "analyze_stats.py", "detruncate.py"]             # first-release analysis, superseded (legacy/v1_analysis/)
DROP = ["grade_v2.py", "smoke_test.py"]                  # an import alias used during the audit; a connectivity check
GH_GLOBS = ["harness/*.py", "harness/run_*.sh", "paper/figures/*.pdf", "gpqa_open_v2/rater1_shard_*.json",
            "gpqa_open_v2/shard_*.json", "audit/*", "docs/*"]

RUNS_FINAL = [
    # analysed inputs (v2): every file the recompute reads (traced), incl. the logged LLM-router picks
    "matrix_marketE3_final.json", "matrix_marketMH_final.json", "matrix_marketCG_final.json", "matrix_marketE2_final.json",
    "matrix_marketGPQAOPENv2.json", "matrix_stageA2v3_final.json", "matrix_hardAv3_final.json", "matrix_churnD_final.json",
    "fusion_eqq2_final.json", "fusion_eqq2_math_final.json", "fusion_eqqA_final.json", "cascade_stageC2v3_final.json",
    "cascade_advC_final.json", "router_llm_stageA2v3_final.json", "items_snapshot.json", "codegen_problems.json",
    "judge_open_v2_meta.json", "code_checker_regrade.json", "rerun_log.csv", "spend_ledger.csv", "cost_registry.csv", "audit_spend.json",
    # correction stages and the first release, so every correction can be diffed
    "matrix_marketE3.json", "matrix_marketMH.json", "matrix_marketCG.json", "matrix_marketE2.json", "matrix_marketGPQAOPEN.json",
    "matrix_stageA2v3.json", "matrix_hardAv3.json", "matrix_churnD.json", "matrix_stageA2v2.json",
    "fusion_eqq2.json", "fusion_eqq2_math.json", "fusion_eqqA.json", "cascade_stageC2v3.json", "cascade_advC.json",
    "matrix_marketE3_rr.json", "matrix_marketMH_rr.json", "matrix_marketCG_rr.json", "matrix_marketE2_rr.json",
    "matrix_stageA2v3_rr.json", "matrix_marketE3_dt.json", "matrix_marketMH_dt.json", "matrix_marketCG_dt.json",
    "matrix_marketE2_dt.json", "matrix_stageA2v3_dt.json",
    # provenance: judge votes, the re-grade report, truncation logs, the code-problem funnel, run metadata
    "judge_open_v2_votes.json", "judge_open_votes.json", "judge_open_meta.json", "regrade_final_report.json",
    "detrunc_v2.log", "detrunc_E2.log", "detrunc_A2.log", "detrunc_mix_final.log", "codegen_problems_raw.json",
    "run_registry.csv",
    # outputs of this version's analysis (regenerated by reproduce.sh; released for inspection)
    "canonical.json", "router_stageA2v3_final.json", "router_hardAv3_final.json", "router_strong_stageA2v3_final.json",
    "rhofus_hardAv3_final.json", "rhofus_stageA2v3_final.json", "eqq_eqq2_final.json", "eqq_eqq2_math_final.json",
    "eqq_robustness_eqq2_final.json", "fusion_analysis_eqq2_final.json", "kstar_eqq2_final.json", "kstar_eqqA_final.json",
    "cascade_analysis_stageC2v3_final.json", "cascade_analysis_advC_final.json", "cascade_heldout_stageC2v3_final.json",
    "churn_churnD_final_mmlu_pro.json", "churn_churnD_final_gsm8k.json", "copula_dichotomy.json",
]


def copy(src, dst):
    os.makedirs(os.path.dirname(dst), exist_ok=True); shutil.copy2(src, dst)


def main():
    card = os.path.join(ROOT, "release", "dataset_card.md")
    keep = open(card).read() if os.path.exists(card) else None     # rendered by scripts/render_docs.py
    for d in (GH, HF):                   # clear the staging folders but keep the GitHub checkout's .git
        if os.path.isdir(d):
            for e in os.listdir(d):
                if e != ".git":
                    p = os.path.join(d, e)
                    shutil.rmtree(p) if os.path.isdir(p) and not os.path.islink(p) else os.remove(p)
    if keep is None:
        raise SystemExit("run scripts/render_docs.py first (release/dataset_card.md missing)")
    for f in GH_FILES:
        copy(os.path.join(ROOT, f), os.path.join(GH, f))
    for g in GH_GLOBS:
        for f in glob.glob(os.path.join(ROOT, g)):
            rel = os.path.relpath(f, ROOT); base = os.path.basename(f)
            if rel.startswith("harness/") and base in LEGACY:
                copy(f, os.path.join(GH, "legacy", "v1_analysis", base))
            elif not (rel.startswith("harness/") and base in DROP) and not rel.startswith("docs/legacy_README"):
                copy(f, os.path.join(GH, rel))
    copy(os.path.join(ROOT, "docs", "legacy_README.md"), os.path.join(GH, "legacy", "v1_analysis", "README.md"))
    os.makedirs(os.path.join(GH, "runs"), exist_ok=True)
    open(os.path.join(GH, "runs", ".gitkeep"), "w").close()
    for f in RUNS_FINAL:
        copy(os.path.join(ROOT, "runs", f), os.path.join(HF, "runs", f))
    for f in ["PROTOCOL.md", "items_original.json", "items_v2.json", "rater1_all.json"]:
        copy(os.path.join(ROOT, "gpqa_open_v2", f), os.path.join(HF, "gpqa_open_v2", f))
    resp = os.path.join(ROOT, "responses", "responses.jsonl.gz")
    if os.path.exists(resp):
        copy(resp, os.path.join(HF, "responses", "responses.jsonl.gz"))
    for f in os.listdir(os.path.join(ROOT, "audit")):
        copy(os.path.join(ROOT, "audit", f), os.path.join(HF, "audit", f))
    copy(os.path.join(ROOT, "DATA_AUDIT.md"), os.path.join(HF, "DATA_AUDIT.md"))
    copy(os.path.join(ROOT, "release", "dataset_card.md"), os.path.join(HF, "README.md"))
    for d in (GH, HF):
        n = sum(len(fs) for _, _, fs in os.walk(d)); size = sum(os.path.getsize(os.path.join(r, f)) for r, _, fs in os.walk(d) for f in fs)
        print(f"[stage] {os.path.relpath(d, ROOT)}: {n} files, {size / 1e6:.1f} MB")


if __name__ == "__main__":
    main()
